name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: spek-X.flatpak
          manifest-path: com.github.MikeWang000000.spek-X.yml
          cache-key: flatpak-builder-${{ github.sha }}
